### ISSUE TITLE
Doesnt seem to work as on 9 Mar 2017

### ISSUE THREAD

**Issue by rravishankar** [aranair/remindbot#1]
I tried to use @hazel_bot on Telegram today and it doesn't work. See attached screenshot. Can you please have it fixed? I'm trying to write my own first bot. Is there a better way other than this ? Also is there something simpler than digital ocean - say some free tier on Google/some other place where I can host this?

![screenshot from 2017-03-09 17 10 10](https://cloud.githubusercontent.com/assets/12893666/23748858/63106a9e-04eb-11e7-83ad-4a18e0d4618e.png)

**Comment by aranair** [comment]
I am currently still using it personally. Have you set it up properly though? Refer to my blog post for a quick guide to set it up! Hmm. I believe that are other VPS services that MIGHT be cheaper than   Digital Ocean, I can't remember the name off hand though.
